export const warmupDrills = [
  {
    name: "Coach Says",
    category: "warmup",
    duration_minutes: 5,
    min_kids: 2, max_kids: 12, min_coaches: 1, max_coaches: 1,
    skill_level_target: "all",
    equipment: [],
    setup_instructions: "No equipment needed. Gather all players in a cluster in the infield grass area between the pitcher's mound and second base. Coach stands about 8 feet in front of the group so everyone can see and hear. Make sure kids are spaced out at least arm's length apart so they don't bump each other — have them stretch their arms out and spin once to check spacing.",
    how_to_explain_to_kids: "We're going to play Coach Says! It's just like Simon Says but with baseball stuff. When I say 'Coach says do this,' you do it. But if I DON'T say 'Coach says' first and you still move — you have to do two jumping jacks! Ready? Let's see who's the best listener on the team!",
    step_by_step: [
      "Gather kids in the infield and have them spread out arm's length apart",
      "Start with 3 easy rounds WITH 'Coach says' to teach the positions — 'Coach says show me batting stance!' then 'Coach says show me ready position!' then 'Coach says catch a pop fly!'",
      "Mix in the first trick — say 'Show me throwing arm!' without 'Coach says' — kids who move do two jumping jacks with you (make it fun, not punishing)",
      "Continue alternating between legitimate calls and tricks, using these baseball positions: batting stance, fielding ready position (knees bent, hands out front), catch a pop fly (hands up, looking up), throw the ball (arm back in throwing position), run to first base (running in place), slide (one leg out like sliding), pitcher windup (hands together overhead)",
      "Speed up the calls as kids get the hang of it — faster pace is funnier and more exciting",
      "Every 60 seconds, call out the kids who haven't been tricked yet — 'Wow, Tommy and Sara are still in!'",
      "For the last round, do 3 rapid-fire calls in a row to catch everyone — end on a big laugh"
    ],
    coaching_points: ["Use this drill to teach real baseball positions — when you say 'batting stance,' quickly check kids' feet and hands and give one fast correction like 'Feet apart, good!' This is sneaky teaching disguised as a game."],
    common_mistakes: [
      "Kids will copy other kids instead of listening to you. Fix: Say 'Close your eyes!' for one round — they have to listen, not watch. Then go back to eyes open. This breaks the copying habit.",
      "Some kids will argue they didn't move when they clearly did. Fix: Don't argue. Say 'I saw a tiny wiggle! Two jumping jacks, let's do them together!' and do the jumping jacks with them so it feels like fun, not a punishment.",
      "Kids will forget what 'ready position' or 'batting stance' means. Fix: The first time you call each position, demonstrate it yourself while saying 'Coach says.' After that, stop demonstrating and make them remember."
    ],
    progressions: "Add two-part commands: 'Coach says batting stance AND catch a pop fly!' — kids have to do both in sequence. Also add 'freeze' as a command where they have to hold whatever position they're in for 5 seconds without wobbling.",
    regressions: "Remove the trick element entirely — just call out positions and let everyone follow along. Turn it into a pure imitation game. Say 'Coach says' before every command so no one gets out. Focus only on learning the 3 easiest positions: batting stance, ready position, and catch a pop fly.",
    fun_factor: 5,
    week_introduced: 1,
  },
  {
    name: "Base Race",
    category: "warmup",
    duration_minutes: 5,
    min_kids: 4, max_kids: 12, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["4 bases (or cones as bases)"],
    setup_instructions: "Use the actual bases on the field if available (60-foot basepaths for T-ball). If no bases, set up 4 cones in a diamond shape 40 feet apart. Split kids into 2 even teams. Team 1 lines up behind home plate. Team 2 lines up behind second base. If you have a second coach, position them at the halfway point (between first and second) to keep kids running the right direction.",
    how_to_explain_to_kids: "Okay, we're going to have a race! This team starts at home plate, this team starts at second base. When I say 'GO,' the first person from each team runs around ALL the bases and comes back. Then you tag the next person's hand, and THEY go! The first team to get everyone around wins! But here's the rule — you HAVE to touch every single base with your foot or it doesn't count!",
    step_by_step: [
      "Split kids into 2 roughly equal teams — put faster kids on the same team as slower kids to balance it out",
      "Line up Team 1 single-file behind home plate, Team 2 single-file behind second base",
      "Demonstrate the path yourself — run and touch each base, exaggerating stepping on each one",
      "First runners from each team step up to their starting base",
      "Yell 'Batter up... GO!' — first runners take off around the bases in order",
      "When a runner gets back to their start, they high-five the next runner who then goes",
      "Coach watches for kids skipping bases — if they miss one, yell 'Go back and touch second!' in a fun voice",
      "First team to have all runners complete the loop wins — losing team does 5 silly jumping jacks",
      "Run it a second time if time allows — kids will beg for a rematch"
    ],
    coaching_points: ["Watch for kids cutting corners and not touching bases — this is actually great base-running practice. Say 'Touch the inside corner of the base with your foot!' which teaches them to take efficient turns just like in a real game."],
    common_mistakes: [
      "Kids will run the wrong way around the bases (going home to third instead of home to first). Fix: Stand at first base and wave your arms yelling 'This way! This way!' For the first round, physically point each runner toward first base as they start.",
      "Kids will not wait for the tag/high-five and will start running early. Fix: Stand near the handoff zone and physically hold the next runner's shoulder, releasing them only when the incoming runner makes contact.",
      "Faster kids will get frustrated waiting for slower teammates. Fix: Give the waiting kids a job — have them cheer by name, 'Go Tommy go!' This keeps them engaged."
    ],
    progressions: "Add a 'backwards race' where kids run the bases in reverse order (home to third to second to first to home). You can also add a rule where they must stop at each base in fielding ready position for 2 seconds before running to the next one.",
    regressions: "Move the cones or bases closer together (30 feet apart). Instead of a full loop, have kids run only to first base and back. Remove the relay element — just have each kid run individually and everyone cheers for them.",
    fun_factor: 5,
    week_introduced: 1,
  },
  {
    name: "Crazy Cones",
    category: "warmup",
    duration_minutes: 5,
    min_kids: 2, max_kids: 12, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["8 cones", "2 pool noodles (optional)"],
    setup_instructions: "Set up a course along the first-base line using 8 cones. Place cones in a zigzag pattern, each cone 5 feet apart. The course should be roughly 40 feet long total. At cone 3 and cone 6, lay a pool noodle flat on the ground for kids to jump over. The finish is at the last cone. If you have a second coach, have them stand at the midpoint to direct traffic.",
    how_to_explain_to_kids: "Check out this crazy course! You're going to zigzag through the cones like a race car, jump over the noodles like a superhero, and do a baseball move at the end! Watch me do it first — weave, weave, weave, JUMP, weave, weave, JUMP, then fielding ready position at the end! Now you try!",
    step_by_step: [
      "Line kids up single-file behind the first cone",
      "Demonstrate the full course yourself — weave through each cone, jump over each pool noodle with two feet, and finish by getting into a fielding ready position at the last cone",
      "Send the first kid through, giving directions as they go — 'Go right! Now left! Jump! Keep going!'",
      "Once the first kid reaches cone 4 (halfway), send the next kid — keep a staggered flow",
      "At the end of the course, the kid does the baseball movement of the round, then jogs back to the start line",
      "After every kid has gone through once, change the baseball movement — Round 2 is batting stance, Round 3 is pretend catching a fly ball",
      "If time allows, challenge kids to beat their own speed on the last run"
    ],
    coaching_points: ["Focus on one thing: keeping their feet moving and staying balanced. Say 'Quick feet! Quick feet!' as they weave. This lateral agility directly helps fielding — they just don't know it yet."],
    common_mistakes: [
      "Kids will run straight through the cones instead of weaving. Fix: On their first time through, walk alongside them and physically guide them — 'This way, now this way.' By the second round they'll understand the pattern.",
      "Kids will stop dead in front of the pool noodle and be afraid to jump. Fix: Hold their hand and jump together the first time. Also lay the noodle completely flat so there's basically no height to clear.",
      "Kids will bunch up and crash into each other. Fix: Use the 'two cone rule' — the next kid cannot start until the kid in front passes the second cone."
    ],
    progressions: "Add a bear crawl section between cones 2 and 3. Raise the pool noodles off the ground by 6 inches. Time each kid and let them try to beat their own time.",
    regressions: "Remove the pool noodles entirely — just a simple weave course. Widen the spacing between cones to 7 feet. Walk through the course with each kid, holding their hand.",
    fun_factor: 4,
    week_introduced: 2,
  },
  {
    name: "Superhero Stretches",
    category: "warmup",
    duration_minutes: 5,
    min_kids: 2, max_kids: 12, min_coaches: 1, max_coaches: 1,
    skill_level_target: "all",
    equipment: [],
    setup_instructions: "No equipment needed. Gather all players in a cluster in the outfield grass or infield area. Coach stands facing the group, about 6 feet in front. Kids should be spaced arm's length apart. Make sure you're positioned so the sun is NOT in the kids' eyes.",
    how_to_explain_to_kids: "We're going to stretch like superheroes! Every stretch has a superhero name. First we're going to be Spider-Man — watch me! Then Superman! Then Batman! Copy what I do and be the BEST superhero you can be. If you do a really good job, I'll let you pick a superhero for the last stretch!",
    step_by_step: [
      "Start with 'Spider-Man Lunges' — step one foot way forward into a lunge, put both hands on the ground like you're about to shoot a web. Hold 5 seconds each side. Say 'Shoot your web! Psshh!'",
      "Next is 'Superman Flying' — stand on one leg, lean forward with arms straight out in front like flying. Hold 5 seconds each leg.",
      "Then 'Batman Squats' — feet wide apart, squat down low, arms crossed in front of chest like Batman's cape. Do 5 slow squats.",
      "Then 'Hulk Smash' — reach arms way up overhead on tippy toes, then SMASH down and touch toes. Do this 5 times.",
      "Then 'Flash Running' — high knees in place as fast as possible for 10 seconds. Coach counts down from 10 loudly.",
      "Finish with 'Wonder Woman Power Pose' — hands on hips, feet apart, chest out, chin up. Hold for 10 seconds.",
      "Ask a kid to pick the final superhero — do that stretch one more time as a group"
    ],
    coaching_points: ["Every single stretch here targets a muscle group used in baseball — lunges for batting/throwing legs, squats for fielding, high knees for running, arm reaches for throwing. You don't need to tell the kids this. Just make the superhero noises and they'll stretch without realizing it."],
    common_mistakes: [
      "Kids will rush through stretches and not actually hold them. Fix: Make every stretch a challenge — 'Can you hold Spider-Man for FIVE whole seconds? Let me count — one Mississippi, two Mississippi...'",
      "Kids will get silly and start wrestling or pushing each other. Fix: Say 'Superheroes stretch ALONE — if you touch someone, you lose your superpowers for that round and have to sit criss-cross until the next one.'",
      "Some kids won't know the superheroes you reference. Fix: Always demonstrate the pose yourself first. The name doesn't matter — they'll copy what they see."
    ],
    progressions: "Have kids hold each pose for 10 seconds instead of 5. Add partner stretches — two kids face each other and mirror the pose.",
    regressions: "Reduce to just 3 stretches instead of 6 — do Spider-Man, Hulk Smash, and Flash Running. Don't worry about holding poses — just do each movement a few times.",
    fun_factor: 4,
    week_introduced: 1,
  },
  {
    name: "Dizzy Bases",
    category: "warmup",
    duration_minutes: 5,
    min_kids: 4, max_kids: 12, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["4 bases (or cones as bases)", "1 bat"],
    setup_instructions: "Use the standard T-ball bases (60-foot basepaths) or set up 4 cones in a diamond 40 feet apart. All players start at home plate in a single-file line. If you have a second coach, position them in the middle of the diamond to point kids toward the correct base and catch anyone who stumbles.",
    how_to_explain_to_kids: "This game is SO funny. Here's what you do. You put the bat on the ground, put your forehead on the knob — that's the top of the bat — and spin around it three times. Then I'm going to yell a base name, and you have to run to THAT base! But you're going to be so dizzy! It's hilarious. Watch me do it first!",
    step_by_step: [
      "Demonstrate the drill yourself first — put a bat on the ground vertically, place your forehead on the knob, spin around 3 times, then run wobbly to a base. Ham it up and stumble.",
      "Line all kids up at home plate. First kid steps forward and grabs the bat.",
      "Coach holds the bottom of the bat on the ground to keep it stable while the kid puts their forehead on the knob.",
      "Count spins out loud with the whole team — 'ONE! TWO! THREE!' — then immediately yell a base: 'FIRST BASE!'",
      "The dizzy kid takes off running toward the called base while everyone cheers and laughs",
      "Second coach stands near the path to catch any kid who wobbles too far off course",
      "Once the runner touches the base, they jog back to the end of the line. Next kid steps up immediately.",
      "Mix up the bases you call — don't always say first base. Yell 'THIRD BASE!' or 'SECOND BASE!'",
      "After everyone goes once, do a second round calling 'HOME RUN!' where they have to run all the way around"
    ],
    coaching_points: ["This is secretly a base-recognition drill. Kids will learn where first, second, and third base are because they HAVE to find them while dizzy. After a few rounds, ask a kid 'Where is second base?' and they'll point right to it."],
    common_mistakes: [
      "Kids will spin too fast and fall down immediately. Fix: Hold the bat steady and count slowly. For very small kids, do only 2 spins.",
      "Kids will run to the wrong base. Fix: Don't correct them — let everyone laugh, then say 'That's third base! I said FIRST base! Try again!' Point at the right base.",
      "A kid will refuse because they're scared of being dizzy. Fix: Let them skip the spinning and just do the running part. Say 'You're our designated runner — no spinning required!'",
      "Kids will crash into each other. Fix: Only one kid spins and runs at a time. Everyone else stays behind the home plate line."
    ],
    progressions: "Increase to 4 or 5 spins for kids who want more challenge. After calling the base, add an action — 'SECOND BASE and show me ready position when you get there!'",
    regressions: "Reduce to 2 spins or even 1 spin. Instead of calling random bases, always call first base so they just run straight ahead. Remove the bat entirely and just have kids spin in place with arms out.",
    fun_factor: 5,
    week_introduced: 2,
  },
];
