export const gameplayDrills = [
  {
    name: "Pickle",
    category: "game_play",
    duration_minutes: 12,
    min_kids: 4, max_kids: 12, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["2 bases (or cones)", "1 tennis ball or soft baseball"],
    setup_instructions: "Set up two bases 45 feet apart along the first-base line or in the infield grass — shorter than a standard basepath because small kids can't throw accurately at full distance. One coach (or experienced kid-tagger) stands at each base to start. Kids line up in a single-file line 10 feet behind one of the bases, waiting for their turn as the runner. The runner starts in the exact middle between the two bases, which is about 22 feet from each one. Use a tennis ball for safety. If you only have one adult coach, two kids can act as taggers at the bases after the first demonstration round.",
    how_to_explain_to_kids: "OK, have you ever heard of a pickle? Not the food — in baseball, a pickle is when you're STUCK between two bases and both fielders are trying to tag you out! You're the runner in the middle. Your job is to get to one of the bases without getting tagged. Pretend you're a super slippery pickle and they can't catch you! The fielders have to throw the ball back and forth and tag you with the ball in their glove. If you get tagged, you go to the back of the line and the next person goes. Ready? Who wants to be the first pickle?",
    step_by_step: [
      "Demonstrate the drill yourself before any kid steps in — have two coaches show how they throw back and forth while a third person acts as the runner and tries to escape",
      "Place two bases 45 feet apart and position one coach or kid-tagger on each base holding the ball; the runner starts at the exact midpoint between them",
      "Coach yells 'PICKLE!' and the runner immediately takes off toward whichever base they choose",
      "The tagger with the ball runs toward the runner while the tagger at the far base holds their glove up and calls 'HERE! HERE!' to receive a throw",
      "The ball gets thrown back and forth between taggers as the runner changes direction — if the runner gets tagged while between bases, they are out and go to the back of the line",
      "If the runner safely reaches either base, they are safe — give them one more attempt before they rotate to the back of the line",
      "Rotate a new runner in every 30-45 seconds so nobody waits more than 90 seconds total; keep the pace fast",
      "After every kid has gone at least once, swap in kids as the base taggers — coach walks them through when to chase and when to throw",
      "Keep a loose count of how many times each runner successfully escapes — kids love knowing their personal escape record"
    ],
    coaching_points: ["Teach the fielder NOT to run all the way to the runner before throwing — the key is to force a throw as soon as the runner changes direction. Tell the tagger: 'When the runner turns around and goes the other way, THROW IT right then.' Running too far before throwing leaves the other base unguarded."],
    common_mistakes: [
      "The runner will pick one base and sprint straight for it without any faking, making the play too simple. Fix: Say 'Try to trick them! Take two big steps this way, then SPIN and go the other way!' Demonstrate a jab step with your own feet. Challenge them: 'Can you get the fielder to throw the ball before you change direction?'",
      "The fielder will hold the ball too long and chase the runner the whole distance instead of throwing early. Fix: Stand next to the tagger and physically tap their throwing arm the moment the runner reverses direction, saying 'THROW — right now!' Give them the visual cue they need until they feel the right timing.",
      "Kids waiting in line will get bored and start wandering after 60 seconds. Fix: Give the line a job — they count out loud how many throws happen before the tag: 'ONE! TWO! THREE!' It keeps them watching every second of the play.",
      "A fielder will try to tag the runner by throwing the ball directly at the runner's body rather than catching it first and touching them with the glove. Fix: Before the drill starts, demonstrate on a coach — catch the ball, close the glove around it, then touch the runner's arm or shoulder with the closed glove. Say it clearly: 'Tag with your glove, never throw at them.'"
    ],
    progressions: "Add a third base so the runner has three options and fielders have to cover more ground. Allow the runner to start on a base and choose their own moment to bolt — they pick when to go. After a few rounds, time how long each runner can survive before being tagged and let kids try to beat the record.",
    regressions: "Shorten the distance between bases to 30 feet so throws are easier to make and control. Tell the runner in advance which base they should sprint to — this removes the faking element and focuses only on running hard through the tag. Use a rolled-up sock as the ball so no kid is nervous about getting hit.",
    fun_factor: 5,
    week_introduced: 4,
  },
  {
    name: "Scrimmage-Lite",
    category: "game_play",
    duration_minutes: 15,
    min_kids: 6, max_kids: 12, min_coaches: 2, max_coaches: 3,
    skill_level_target: "all",
    equipment: ["4 bases", "1 batting tee (backup)", "1 safety baseball or tennis ball", "batting helmets", "1 bat"],
    setup_instructions: "Use the full T-ball field with bases at 60-foot spacing. Split kids into two teams of 3-6. The batting team lines up single-file along the first-base fence or in the dugout area. The fielding team spreads out: one kid at the pitcher's mound area (about 15 feet from home plate), one at first base, one at second base, and any remaining kids spread in the outfield grass between the infield and the fence. Coach pitches from 15-18 feet in front of home plate, underhand with a slow looping arc — aim for the batter's belly button. Keep the batting tee set up next to home plate at all times as a backup. The half-inning ends after 3 outs OR 5 runs score, whichever comes first.",
    how_to_explain_to_kids: "We're going to play a REAL baseball game right now! I'm going to pitch to you nice and easy — not fast, just a big loopy toss. When you hit it, drop the bat to the side and RUN to first base as hard as you can! If you're already on a base, watch your base coach — they'll yell GO or STOP, and you follow what they say. The fielding team is going to grab the ball and throw it to a base to try to get you out. We play until three outs or five runs — then the teams switch. Play ball!",
    step_by_step: [
      "Assign teams — count off by twos, or use pinnies if available; balance skill levels so both teams have a mix of stronger and newer players",
      "Fielding team takes positions — put the most confident thrower at first base, spread remaining kids at second base, shortstop area, and outfield; coach walks each kid to their exact spot",
      "First batter puts on a helmet and steps into the batter's box — coach pitches from 15-18 feet, underhand, aiming for the belly; batter gets 4 pitches, then one tee swing if no contact",
      "After contact, batter drops the bat to the side and runs hard to first base — a second coach stationed just behind the batter yells 'GO GO GO!' the instant the ball is hit",
      "Fielding team retrieves the ball and throws to first base for an out — use force outs only for now (ball beats runner to the base), no tagging required; this keeps it simple",
      "Base coaches use two signals only: both hands down flat means STOP, big windmill arm wave means GO — practice these signals with the kids before the first pitch",
      "After 3 outs OR 5 runs score, teams switch — the group coming in from the field gets 60 seconds to find their batting order position before the first pitch goes",
      "Coach in the field continuously directs throws: 'First base! Second base! First base!' — players should not have to guess where the ball is going",
      "Keep the pace moving — the moment a play is dead, the next batter walks to the plate; aim for a new at-bat every 60-90 seconds"
    ],
    coaching_points: ["Your one job as base coach is to give ONE clear, loud signal — STOP (hands down) or GO (big arm wave). Never say 'maybe' or 'if the ball drops then try.' Kids cannot process conditional logic while running at full speed. Commit to a call the moment the ball is fielded, and say it loud enough to be heard over the chaos."],
    common_mistakes: [
      "All fielders will swarm every batted ball like bees, leaving every base uncovered. Fix: Before the inning starts, walk to each fielder's position and draw a circle in the dirt at their feet. Say 'This is YOUR area — if the ball comes into your circle, you get it. If it doesn't, stay here and be ready for a throw.'",
      "Batters will stand at home plate watching their hit instead of running. Fix: Position a coach one step behind the batter's box whose only job is to yell 'GO GO GO!' the instant bat meets ball — every single at-bat, no exceptions.",
      "Fielders in the outfield will sit down and pick grass because nothing comes to them for several minutes. Fix: Rotate outfielders to infield positions every 3 batters. Give outfielders a specific assignment: 'You are backup for any ball that gets past the infield — if it rolls out there, that's YOUR ball.'",
      "Batters will drop the bat directly on top of home plate, then trip over it while running to first. Fix: Before every single at-bat, say 'After you hit it, drop the bat to THIS side' and mime dropping it safely to the right of the plate. Say this every time, for every batter, until it becomes automatic."
    ],
    progressions: "Introduce one tagging rule — runners can be tagged out on the basepaths in addition to force outs. Allow runners already on base to advance on a passed ball. Give the fielding team a celebration point for any clean throw to first that beats the runner by two steps.",
    regressions: "Use the tee for every single batter instead of coach pitching. Remove outs entirely — every batter gets on base, every runner scores, the goal is just for everyone to experience hitting and running the bases. Put a coach at first base and second base to physically guide runners where to go.",
    fun_factor: 5,
    week_introduced: 5,
  },
  {
    name: "Situation Ball",
    category: "game_play",
    duration_minutes: 12,
    min_kids: 4, max_kids: 12, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["4 bases", "1 tennis ball or soft baseball", "3-4 cones"],
    setup_instructions: "Use the full infield with all four bases at 60-foot spacing. Place 3-4 cones on the outfield grass at 80 feet from home plate to mark the boundary where a ball becomes an outfield grounder versus an infield play. Position 4-6 kids at fielding spots — pitcher's mound area, first base, second base, and shortstop area between second and third; remaining kids wait along the fence and rotate in every 2-3 scenarios. One coach stands at home plate to announce scenarios and roll or throw the ball. A second coach stands near the second-base area to direct throws in real time.",
    how_to_explain_to_kids: "This game is called Situation Ball and it's my favorite because YOU have to be the smart one — not me. I'm going to put a pretend runner on a base and then hit or roll the ball somewhere on the field. Your job is to figure out: where does the ball go? Which base do you throw to? Here's the secret — there's usually a right answer, and I want YOU to find it. It's like a puzzle. I'll help you figure it out after every play. Ready to be the smartest team in the league?",
    step_by_step: [
      "Start with the absolute simplest scenario — no runners on base, grounder to first baseman. Ask the group before rolling: 'If I hit it to the first baseman right now, where should they throw it?' Let them answer.",
      "Roll or throw a firm grounder to the first baseman, call their name first so they know it's coming: 'Maya — here it comes!' — let them field it and make the throw",
      "After every single play, stop everything for a 30-second debrief: 'What did Maya do? Where did she throw? Was that the right call? What else could she have done?'",
      "Run the same scenario 2-3 times with different fielders so multiple kids get the repetition and the group reinforces the right answer together",
      "Add a runner: place a coach or another kid on first base. Announce: 'Runner on first! I hit it to the shortstop — where does it go?' Let them discuss, then execute",
      "After the play, gather and debrief again — this discussion time is not wasted, it is the entire point of the drill",
      "Gradually build up scenario complexity: runner on second only, runner on third only, runners on first and second — introduce each new situation only after the previous one feels solid",
      "After 5-6 scenarios, let a kid be the 'field manager' who tells the coach where to place the runners and announces the scenario to the rest of the team",
      "End every session with one championship scenario — 'Bases loaded, two outs, you need this one out to win the game' — and let the team talk through the play before anyone moves"
    ],
    coaching_points: ["Do not give the answer before the play happens. Let them make the decision — even the wrong one — then talk about it after. A kid who throws to the wrong base and then hears why it was wrong will remember that lesson for the rest of the season. If you tell them the answer first, it becomes a robot drill with no learning."],
    common_mistakes: [
      "A fielder will catch or field the ball and then freeze, staring around with the ball in their hand because they have no idea where to throw. Fix: Before rolling the ball, give them a simple default rule to fall back on every time: 'When you are not sure, throw to first base. First base is always a safe answer.' Repeat this until it's their automatic instinct.",
      "All the kids will yell different bases at the fielder at the same time while the play is happening, causing total confusion. Fix: Establish the 'one voice rule' before the first scenario — only the fielder's assigned base coach may call a target during a live play. Everyone else cheers, nobody directs. Violators owe five jumping jacks.",
      "The baserunner will stand still on the base instead of running, making the scenario feel fake and low-stakes. Fix: Tell the runner before each play: 'The second I roll the ball, you take off and run as hard as you can — you're the fastest runner in the league and they have to try to stop you.' Give them ownership of their role.",
      "Kids waiting on the sideline will shout 'WRONG!' at the fielder before the coach can lead the debrief, embarrassing the fielder and shutting down the learning moment. Fix: Set this rule at the very start: 'After every play we all freeze, and ONLY I talk first. Then I ask what you think. If anyone yells an answer before I ask, they sit out the next scenario.'"
    ],
    progressions: "Have the baserunner actually run at full speed during the play so fielders must make the throw in real time under pressure. Introduce back-to-back scenarios with no debrief in between — let them run two plays, then discuss both. Add a time limit: fielder must release the throw within 3 seconds of fielding the ball.",
    regressions: "Eliminate the baserunner entirely and work only on where to throw a ball with nobody on the bases. Repeat the exact same scenario — no runners, grounder to shortstop, throw to first — for the entire drill until every kid can execute it without any prompting. Walk through each play in slow motion before adding any game speed.",
    fun_factor: 4,
    week_introduced: 6,
  },
  {
    name: "World Series",
    category: "game_play",
    duration_minutes: 15,
    min_kids: 6, max_kids: 12, min_coaches: 2, max_coaches: 3,
    skill_level_target: "all",
    equipment: ["4 bases", "1 batting tee", "1 safety baseball or foam ball", "batting helmets", "1 bat", "2 sets of pinnies or colored jerseys"],
    setup_instructions: "Use the full T-ball field with bases at 60-foot spacing. Split kids into two named teams using pinnies — if you have 8 kids, teams of 4. Batting team lines up single-file along the first-base fence behind the dugout area. Fielding team takes the field: one kid at first base, one near second base, one at shortstop, any remaining kids spread in the outfield grass between the infield dirt and the outfield fence. Ball goes on the tee at home plate. Coach pitches from 15-18 feet underhand or uses the tee — dealer's choice based on how the kids are hitting that day. The non-negotiable rule: EVERY kid on the batting team bats in each half-inning before the teams switch, regardless of how many outs occur. Treat this like the championship game it is.",
    how_to_explain_to_kids: "Okay everyone, listen up — this is the WORLD SERIES. The biggest game of the entire year. This team is the (name) and this team is the (name). Every single person on your team is going to bat this inning — nobody sits out, nobody skips. When you're in the field you play as hard as you can and try to get outs. When you bat, you hit it as far as you possibly can and run like your cleats are on fire. We are playing for the championship right now. Are you READY?!",
    step_by_step: [
      "Let each team pick their team name — give them 60 seconds and two options to vote between if they can't agree ('Are you the SHARKS or the THUNDER?'); immediately do a 10-second team cheer so the identity is real before the first pitch",
      "Flip a coin or do rock-paper-scissors to decide who bats first — make it a loud, dramatic moment that the whole group watches",
      "Write the batting order on the back of your hand or a notepad before the first pitch — every kid's name, in order, so nobody is skipped or forgotten",
      "Every batter gets 4 pitches from the coach, then one tee swing if no contact — no strikeouts, no walks, everyone makes contact and runs",
      "After every batted ball, everyone plays hard — fielders go for real outs (throws to first, fly ball catches), baserunners run hard and read their base coach",
      "After every kid on the batting team has batted regardless of outs, count the runs and announce the score dramatically and loudly: 'Tigers have THREE! Cubs need FOUR to win!'",
      "Switch teams — the fielding team comes to bat with the score announced, the stakes are real",
      "If the game is tied after both teams bat, run one bonus round: one batter per team, coach pitches, whoever scores or gets out first decides the winner",
      "Winning team does a full victory lap around all four bases while the other team lines up at home plate and gives them a clap-out as they cross home — then immediately announce 'REMATCH NEXT WEEK'"
    ],
    coaching_points: ["The scoreboard is the motivation. Say the score loudly and often during the half-inning — 'Tigers have 2 runs! Cubs still have zero!' Four-year-olds will dig deeper and play harder than you have ever seen when they know the score and the game is close. Manufacture drama if you have to — make every moment feel like the bottom of the ninth."],
    common_mistakes: [
      "Every fielder will sprint toward the batted ball regardless of position, leaving all bases uncovered. Fix: Before the inning starts, walk each fielder to their exact position and give them a physical landmark to anchor to — 'Jaylen, your spot is right next to second base. Keep one foot touching the bag until the ball comes into your area.'",
      "The batting order gets confused and kids argue about whose turn it is. Fix: The batting order is written on your hand and you call the name loudly before each at-bat. The next batter stands in the on-deck area (one step from the plate) while the current batter hits. Zero debate, zero delay.",
      "The winning team will gloat and the losing team will cry or shut down emotionally. Fix: Immediately after the final out, give the losing team power — 'Losing team picks what team cheer we all do together right now.' Both teams do the cheer together as one group. This reframes the ending so everyone leaves on the same positive note.",
      "The game bogs down with long pauses between at-bats and fielders lose focus. Fix: The moment a play ends, the next batter is already walking to the plate. Keep a spare ball near the mound so the coach never has to chase a foul ball — grab the spare and keep going. No play should ever wait more than 20 seconds between pitches."
    ],
    progressions: "Add a two-inning format where runs accumulate across both innings and the deficit can be overcome. Introduce one real game rule each week as kids are ready: runners can advance on a passed ball, outfield fly catches are outs, overthrows give runners one extra base. Let a kid volunteer to be the first-base umpire and make the call.",
    regressions: "Remove all outs — every kid bats and every kid runs all the way around the bases to score. No outs, no pressure, no score, just the joy of hitting and running. Use the tee for every single batter. Focus entirely on each kid's individual at-bat experience and celebrate every single hit equally.",
    fun_factor: 5,
    week_introduced: 7,
  },
  {
    name: "Relay Race Throw",
    category: "game_play",
    duration_minutes: 10,
    min_kids: 4, max_kids: 12, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["2 tennis balls or soft baseballs", "4 cones"],
    setup_instructions: "Set up two parallel relay lines in the outfield grass, running in the same direction roughly from the left-field foul line toward center field — you need a flat open stretch of about 60-70 feet. Each line has kids standing 20 feet apart from the person in front of them and behind them. To measure 20 feet without a tape, have two kids face each other and both stretch their arms out — when their fingertips almost but don't quite touch, they're approximately the right distance apart. Mark the start of each line with a cone and the end of each line with a cone. The two lines run parallel about 15 feet apart from each other so one coach can watch both. Each line starts with a ball at the front kid.",
    how_to_explain_to_kids: "We're having a race — but not a running race, a THROWING race! Your whole team is in a line. The first person throws to the second person. The second throws to the third. All the way to the end! When it gets to the last person, they throw it all the way BACK up to the front! First team to get the ball back to the start person — and that person holds it up in the air — WINS! If you drop it, no big deal, just pick it up right where you are and keep throwing. Ready? On your mark, get set — THROW!",
    step_by_step: [
      "Split kids into two even teams — if you have an odd number, a coach fills the empty spot in the shorter line",
      "Have each team line up with 20 feet between players — coach checks spacing by standing between two kids and making sure both feel like a challenging but makeable throw",
      "Put one strong thrower near the front and one near the back of each line so the ball can actually cover the full distance even if a mid-line kid struggles",
      "Give the first kid in each line the ball — coach counts down: 'On your mark, get set — THROW!'",
      "Ball travels down the line one throw at a time — each kid catches or retrieves the ball and throws immediately to the next person in line",
      "When the ball reaches the last kid, they hold it up and yell 'TURN!' then immediately throw it back toward the front of the line",
      "Ball travels all the way back — when the first kid catches it and holds it overhead, that team wins the round",
      "Coach watches for skipped kids — if a ball gets thrown over someone, that team must go back and redo the throw from the skipped person",
      "Run three total rounds, rotating who stands at the front of the line so the starting position cycles through the team; the final round requires every thrower to say the receiver's name out loud before releasing the ball — 'SOFIA, HERE!'"
    ],
    coaching_points: ["Watch kids' feet every throw — most will stand square-on and lob the ball with zero body involvement. Say 'Step toward your teammate with your front foot before you throw' and demonstrate it with a big exaggerated step. Give this cue on every single throw for the first round. Footwork is the one thing that immediately improves both distance and accuracy at this age."],
    common_mistakes: [
      "Kids will throw too hard and sail the ball way over their teammate's head, and it rolls 30 feet before anyone can get it. Fix: Before the race, tell every thrower: 'Throw soft enough that your teammate can catch it at their belly button — aim for the belly, not the sky.' If throws are still going wild after round one, shorten the spacing to 15 feet without making a big deal of it.",
      "Kids will drop the ball and then freeze, staring at it on the ground while teammates yell at them, causing a panic spiral. Fix: Before the drill starts, say loudly and clearly: 'If you drop it — and somebody WILL drop it, that is totally fine — just pick it up fast and throw. We are here to practice, not to be perfect.' Celebrate the first person who picks up a dropped ball quickly.",
      "The faster team finishes first and immediately starts yelling at and taunting the other team, which causes the slower team to rush and make more errors. Fix: After round one, give the winning team a built-in 5-second delay before they can start round two — 'Winners wait for my signal.' This naturally balances the competition without embarrassing anyone.",
      "Kids will drift toward the ball to catch it instead of staying in their spot, which compresses the line and defeats the purpose of the drill. Fix: Before the race, place a cone directly next to each kid's feet and say clearly: 'Your feet stay next to your cone until you have the ball in your hands and you have thrown it. The cone is your home base.'"
    ],
    progressions: "Increase spacing to 30 feet between players for kids who demonstrate consistently catchable throws. Add a rule that every throw must arrive in the air — no one-bounce throws allowed. Run both balls simultaneously on the same team going in the same direction to create a chaotic challenge that requires communication.",
    regressions: "Shorten spacing to 12 feet between players. Allow one bounce per throw before the receiver catches it. Remove the race element entirely — one team throws the ball down and back while a coach counts the seconds, then they try to beat their own time. This shifts focus from competing against the other team to competing against themselves.",
    fun_factor: 5,
    week_introduced: 3,
  },
];
