// Additional drills to reach 40+ total
export const extraDrills = [
  {
    name: "Bucket Brigade",
    category: "fielding",
    duration_minutes: 7,
    min_kids: 3, max_kids: 6, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["tennis balls (6+)", "3 buckets or cones", "gloves for each kid"],
    setup_instructions: "Set up 3 buckets (or cones) in a line from shortstop to first base, each about 12 feet apart. Place one kid at each bucket. Coach stands at home plate with a pile of tennis balls. Remaining kids line up behind the first bucket to rotate in. This simulates a relay throw from the outfield to the infield.",
    how_to_explain_to_kids: "We're going to play bucket brigade! I'm going to hit a grounder to the first person. You field it and throw it to the next person, and THEY throw it to the next person, and it goes all the way to the last bucket! It's like a chain — each person is a link! If the chain breaks, we start over. Let's see how many we can get all the way through!",
    step_by_step: [
      "Place one kid at each of the 3 positions in the relay line, about 12 feet apart",
      "Coach hits or rolls a grounder to kid #1 (closest to home plate)",
      "Kid #1 fields it and throws to kid #2. Say 'Quick hands!' as the ball moves",
      "Kid #2 catches and throws to kid #3. Kid #3 drops it in the bucket or holds it up",
      "If the ball makes it all the way through cleanly, everyone cheers and the team gets a point",
      "If a ball is dropped, say 'Almost! Reset!' and go again immediately",
      "After 3 rounds, rotate positions — everyone gets to play each spot",
      "Challenge round: 'Can we get 3 in a row without dropping it?'"
    ],
    coaching_points: ["TWO cues: 'Quick hands' and 'Chest high throws.' The goal is smooth, fast transfers — field it, turn, throw. Don't worry about footwork at this age. If the ball gets from kid #1 to kid #3, that's a win."],
    common_mistakes: [
      "The first kid fields the ball and then pauses, looking around confused about where to throw. Fix: Before the first round, have each kid point to who they're throwing to. Say 'You throw to HER. You throw to HIM.' Walk through it without a ball once.",
      "Throws go over heads or into the dirt between kids. Fix: Shrink the distance to 8 feet. Remind them: 'Throw to their chest, not their head.' If throws are consistently wild, have them take one step toward their target before throwing."
    ],
    progressions: "Increase the distance between kids to 15-18 feet. Add a fourth kid in the chain. Time the relay — how fast can the ball get from start to finish? Have the coach hit actual grounders instead of rolling them.",
    regressions: "Shrink to 8 feet between kids. Use a foam ball. Remove the fielding component — just have them pass the ball hand-to-hand to learn the relay concept. Coach stands in the middle and helps redirect errant throws.",
    fun_factor: 4,
    week_introduced: 5,
  },
  {
    name: "Capture the Base",
    category: "game_play",
    duration_minutes: 10,
    min_kids: 6, max_kids: 12, min_coaches: 2, max_coaches: 4,
    skill_level_target: "all",
    equipment: ["4 bases", "8 wiffle balls or tennis balls", "2 buckets"],
    setup_instructions: "Set up a diamond with all four bases. Place a bucket at home plate and another at second base. Scatter 8 wiffle balls randomly around the infield and outfield. Split kids into two teams — one team starts at home plate, the other at second base. Each team's goal is to collect balls and bring them back to their bucket. Coaches station themselves at first and third base to supervise and enforce rules.",
    how_to_explain_to_kids: "This is CAPTURE THE BASE! See all those balls on the field? Your team has to grab them and bring them back to YOUR bucket. But here's the rule — you can only carry ONE ball at a time! And you have to RUN — no walking! The team with the most balls in their bucket when I blow the whistle WINS! Ready? GO!",
    step_by_step: [
      "Split kids into two teams. Each team huddles at their base (home plate or second base).",
      "Explain the rules: one ball at a time, must run, drop the ball in your bucket, then go get another",
      "Say 'Ready, set, GO!' and start a 2-minute timer",
      "Kids sprint to grab balls and run them back to their bucket. Coaches keep count.",
      "At the 1-minute mark, yell 'ONE MINUTE LEFT!' to increase urgency",
      "When time's up, count each bucket. Most balls wins Round 1.",
      "Round 2: Add a twist — 'You can now STEAL one ball from the other team's bucket!'",
      "Play 3 rounds, mixing up the starting positions and ball placement each time"
    ],
    coaching_points: ["This is pure conditioning and hustle disguised as a game. Kids are sprinting, bending down to pick up balls, and running back — fielding and baserunning muscles in action. Don't coach mechanics here. Just yell encouragement and keep score."],
    common_mistakes: [
      "Kids will grab multiple balls at once. Fix: The rule is simple — 'ONE ball! If I see two balls in your hand, you have to put them BOTH back!' Enforce it immediately the first time and it won't happen again.",
      "Kids will walk instead of run. Fix: Narrate like a sportscaster. 'Oh look at Tommy SPRINTING! He's the fastest on the field!' Peer pressure and hype get them running.",
      "Arguments about which balls belong to whom. Fix: Use different colored balls if possible. If not, the coach's count is final. Say 'Coach's eyes are the referee. No arguments!'",
      "Kids will crash into each other going for the same ball. Fix: Before round 2, say 'If two people reach for the same ball, the person who gets there FIRST keeps it. The other person runs to a different ball. No grabbing!'"
    ],
    progressions: "Add a 'stealing' round where kids can take one ball from the other team's bucket (but they risk wasting time). Increase the field size by scattering balls into the outfield. Add a rule that you must do a jumping jack before putting the ball in the bucket.",
    regressions: "Remove the competition — just have all kids on one team trying to get all 8 balls into one bucket before the timer runs out. Shorten the distances by placing balls closer to the buckets. Let kids walk if running is too chaotic.",
    fun_factor: 5,
    week_introduced: 3,
  },
  {
    name: "Soft Toss Swings",
    category: "hitting",
    duration_minutes: 8,
    min_kids: 2, max_kids: 4, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["bat (youth)", "wiffle balls (10+)", "bucket", "batting tee (backup)"],
    setup_instructions: "Coach kneels to the side of home plate, about 4 feet away from the batter, at roughly a 45-degree angle. This is the 'soft toss' position — you flip balls underhand from the side, not from in front. Place a bucket of wiffle balls next to the coach. Have a second bucket or net 20-30 feet in front of home plate to collect hit balls. Keep the tee nearby for beginners who struggle with the moving ball.",
    how_to_explain_to_kids: "I'm going to flip the ball to you from right HERE — right to your bat. It's like the ball is floating in the air right in front of you. All you have to do is SMASH it! Watch — I flip, you swing! It's that easy. And don't worry, the ball is coming from the side, not at your face. Ready? Let's smash some balls!",
    step_by_step: [
      "Kneel to the batter's front side, about 4 feet away, at a 45-degree angle",
      "Show the batter where you'll flip the ball — hold one up in the toss zone (belt high, out front of home plate)",
      "Say 'Ready?' and when the batter nods, flip the ball underhand with a gentle arc so it peaks about 2 feet above the strike zone and drops into the hitting area",
      "The batter swings at the ball as it drops into the zone. Say 'Nice!' on any contact.",
      "Repeat quickly — flip, swing, flip, swing. Aim for 10 flips per batter in about 60-90 seconds.",
      "After 10 swings, the batter collects the hit balls while the next kid steps in",
      "If a kid is missing badly, switch to the tee for 5 swings to rebuild confidence, then try soft toss again",
      "Final round: 'Power swings only! Show me your biggest, best swing!'"
    ],
    coaching_points: ["ONE cue: 'Let it drop, then swing.' Kids will swing as soon as they see the ball leave your hand — way too early. The ball needs to drop into the zone first. Say 'Wait for it... NOW!' on the first few to teach the timing. After that, just flip and let them figure out the rhythm."],
    common_mistakes: [
      "The coach flips the ball too fast or too far from the batter. Fix: The flip should be SUPER slow — a gentle lob with almost no speed. And it should land right in the batter's sweet spot. If the kid has to reach for it, you're tossing too far away. Move closer.",
      "Kids swing way before the ball arrives. Fix: Have them keep the bat on their shoulder until you say 'NOW.' Flip the ball, wait until it's in the zone, then say 'NOW!' After 5 reps, they'll start to feel the timing on their own.",
      "The coach gets hit by the bat. Fix: ALWAYS kneel to the FRONT of the batter (the side they're swinging toward), never behind them. Stay low. If you're positioned correctly, the bat swings away from you, not toward you. This is critical for safety."
    ],
    progressions: "Speed up the toss slightly. Toss from different heights — low tosses, belt-high tosses, high tosses — to teach adjusting the swing. Move from soft toss to front-toss (kneeling 10 feet in front of the batter behind an L-screen or from one knee).",
    regressions: "Make the toss almost a hand-placement — gently place the ball in the air 12 inches from the bat. Use jumbo wiffle balls. If they still can't time it, go back to the tee and just work on contact. Soft toss is a step UP from the tee, not a replacement.",
    fun_factor: 4,
    week_introduced: 5,
  },
  {
    name: "Outfield Fly Challenge",
    category: "fielding",
    duration_minutes: 7,
    min_kids: 2, max_kids: 5, min_coaches: 1, max_coaches: 1,
    skill_level_target: "all",
    equipment: ["tennis balls (5+)", "gloves for each kid", "4 cones"],
    setup_instructions: "Set up 4 cones in a 20-foot square in the outfield grass — this is the catching zone. Coach stands about 20 feet from the center of the square. Kids line up behind one of the cones. Use tennis balls only. The square helps kids understand the idea of covering a zone — the ball could land anywhere inside it.",
    how_to_explain_to_kids: "I'm going to hit some FLY BALLS into the air, and you have to run and catch them! But they could go ANYWHERE in this big square. You have to watch the ball and move your feet to get under it. Remember your ice cream basket? Hands out like a bowl! If you catch it, that's 3 points. If you get a hand on it, that's 1 point. Let's go!",
    step_by_step: [
      "First kid jogs to the center of the square and gets in ready position — knees bent, weight on toes",
      "Coach tosses a fly ball (underhand, high arc) somewhere inside the square — not right at the kid, make them move a few steps",
      "Yell 'BALL!' as you toss it so they look up immediately",
      "The kid moves to get under it and tries to catch it basket-style",
      "After the catch attempt, they toss the ball back and the next kid rotates in",
      "Each kid gets 3 fly balls per round. Mix directions — left, right, in front, behind them.",
      "After everyone goes once, increase the height and distance of the tosses",
      "Challenge round: 'Can you catch 2 out of 3?'"
    ],
    coaching_points: ["ONE cue: 'Move your feet first, THEN catch.' Most missed fly balls happen because the kid doesn't move — they stand flat-footed and reach. If you see them shuffling their feet to get under the ball, celebrate it even if they drop it. 'Great feet! You were right there!'"],
    common_mistakes: [
      "Kids will stand still and reach with their glove instead of moving their feet. Fix: Before starting, throw 3 balls WAY to the left. Say 'RUN to it!' They have to sprint. This establishes that fly balls require movement, not reaching. Then mix in some easier ones right at them.",
      "Kids are terrified of the ball coming down on their head. Fix: Use tennis balls only. Start with low tosses (8-10 feet high). Let them catch bare-handed first so they can feel the ball is soft. Work up to higher tosses gradually.",
      "They try to catch it over their head instead of at chest level. Fix: Say 'Catch it in your basket, not on your head. Bowl of ice cream, remember?' If the ball is coming down right on them, teach them to take one step back so the ball drops into their chest-level basket."
    ],
    progressions: "Increase toss height to 30+ feet. Use a tennis racket or bat to hit actual fly balls that go higher and less predictably. Have them catch and throw to a cutoff man. Add calling 'I got it!' before catching — essential for game play.",
    regressions: "Shrink the square to 10 feet. Toss directly at the kid (no movement required). Use foam balls. Toss only 5-6 feet high. Let them trap the ball against their body instead of basket catching.",
    fun_factor: 4,
    week_introduced: 6,
  },
  {
    name: "Around the Horn",
    category: "throwing",
    duration_minutes: 7,
    min_kids: 4, max_kids: 6, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["1 tennis ball", "gloves for each kid", "4 bases"],
    setup_instructions: "Put one kid at each base — home, first, second, third. If you have 5-6 kids, put extras at second base and shortstop position. Use the standard T-ball diamond (50-foot basepaths) or shrink to 35-foot distances with cones if 50 feet is too far for accurate throwing. Coach stands in the pitcher's mound area to direct traffic and retrieve wild throws.",
    how_to_explain_to_kids: "We're going to throw the ball AROUND THE HORN! That means around all the bases. I'll start at home plate and throw to first. First throws to second. Second throws to third. And third throws it BACK to home. That's 'around the horn!' In real baseball, they do this after every strikeout. Let's see how fast we can do it!",
    step_by_step: [
      "Place one kid at each base. Show them the sequence: home → first → second → third → home",
      "Start with the ball at home plate. The kid at home throws to first base.",
      "First base catches it and throws to second. Coach says 'Nice! Keep it going!'",
      "Second throws to third. Third throws home. If it makes it all the way around, everyone cheers.",
      "If a throw is wild, coach retrieves the ball and hands it to whoever was supposed to catch it. Say 'Reset! Keep going!'",
      "Time the first successful round: 'That took 15 seconds! Let's beat it!'",
      "Rotate positions after every 2 successful trips around the horn",
      "Final challenge: 'Can we go around the horn in under 10 seconds?'"
    ],
    coaching_points: ["TWO cues: 'Step toward your target' and 'Chest-high throw.' The kid receiving the ball should hold their glove out as a target — say 'Show your buddy where to throw.' At this age, just getting the ball from one base to the next is a massive accomplishment."],
    common_mistakes: [
      "Throws go everywhere — over heads, in the dirt, to the wrong base. Fix: Shrink the diamond to 25-30 feet. Even at 50 feet, most 4-year-olds can't throw accurately. A smaller diamond means more completions, which means more fun and better practice. You can always expand later.",
      "Kids throw to the wrong base — second throws to home instead of third. Fix: Before starting, walk the sequence. Stand at second and point to third: 'You throw to HIM.' Stand at third and point to home: 'You throw to HER.' Do a dry run — point at each base in order, no ball.",
      "The kid at the receiving base isn't ready — they're looking at bugs or talking to a friend. Fix: The coach calls out each throw before it happens: 'Home to first — READY? THROW!' Then immediately: 'First to second — READY? THROW!' The verbal countdown keeps everyone alert."
    ],
    progressions: "Increase to full 50-foot bases if throwing accuracy improves. Go around twice without stopping. Add a 'reverse horn' — go the other direction (home → third → second → first → home). Time the team and track their best time across practices — create a 'record' to beat.",
    regressions: "Shrink to 20-foot distances. Use foam balls. Have the coach stand in the middle and relay — kid throws to coach, coach tosses to next base — until they build enough arm strength. Just do home to first and back, then add bases one at a time.",
    fun_factor: 4,
    week_introduced: 6,
  },
];
