export const hittingDrills = [
  {
    name: "Tee Ball Blast",
    category: "hitting",
    duration_minutes: 8,
    min_kids: 2, max_kids: 4, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["batting tee", "wiffle balls (10+)", "bat (youth)", "bucket", "3 cones"],
    setup_instructions: "Set tee at home plate. Place bucket 40 feet straight ahead (near pitcher's mound area). Set 3 cones in a line 5 feet apart starting 30 feet from home plate to mark distance zones. Have 10+ wiffle balls ready in a pile next to the tee.",
    how_to_explain_to_kids: "Okay guys, we're going to blast the ball off the tee! See those cones out there? Each one is worth more points — the farther you hit it, the more points you get! Let's see who can get the most points in 5 swings. Ready? Step up to the plate!",
    step_by_step: [
      "Line kids up behind home plate, first kid steps up",
      "Place wiffle ball on tee, adjust tee height to kid's belt level",
      "Remind them: feet apart, bat back, eyes on the ball",
      "Say 'Swing!' and let them hit",
      "After the hit, quickly place next ball while another kid retrieves",
      "Each kid gets 5 swings then rotates to the back",
      "Keep a fun score — celebrate every hit that goes past the first cone",
      "After everyone has gone once, do a second round if time allows"
    ],
    coaching_points: ["Watch for the front foot step — they should step TOWARD the ball, not away. Say 'Step to the ball!' before each swing."],
    common_mistakes: [
      "Kids will look up before they swing to see where the ball goes. Fix: Put your hand on top of the tee and say 'Watch my hand, hit under my hand.' Remove hand right before they swing. This trains their eyes to stay down.",
      "Kids will chop down at the ball. Fix: Say 'Swing flat like a pancake, not like chopping a tree.'"
    ],
    progressions: "Move the tee slightly in front of home plate so the kid has to reach forward — teaches contact point out front. Also try soft-toss from the side instead of the tee for advanced kids who are making consistent contact.",
    regressions: "Use a bigger wiffle ball (jumbo size if available). Move the point cones closer (15 feet). Any contact at all gets a cheer — don't mention direction or distance for beginners, just celebrate the hit.",
    fun_factor: 5,
    week_introduced: 1,
  },
  {
    name: "Beat Your Score",
    category: "hitting",
    duration_minutes: 8,
    min_kids: 2, max_kids: 4, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["batting tee", "wiffle balls (10+)", "bat (youth)", "4 cones", "dry-erase board or notepad"],
    setup_instructions: "Set up the tee at home plate. Place 4 cones in a straight line at 10 feet, 20 feet, 30 feet, and 40 feet. These mark scoring zones: Zone 1 = 1 point, Zone 2 = 2 points, Zone 3 = 3 points, Zone 4 = 5 points. Write each kid's name on a dry-erase board before starting.",
    how_to_explain_to_kids: "Today is all about YOU beating YOUR score — not anyone else's. I'm going to write down your name and your score. You get 5 swings, and every swing earns points based on how far it goes. After everyone goes, we'll do it again, and you try to beat YOUR OWN number. Can you beat yourself? I bet you can!",
    step_by_step: [
      "Write every kid's name on the board with a blank spot for Round 1 and Round 2 scores",
      "First kid steps up. Adjust tee to belt height. Place wiffle ball on tee.",
      "Coach says 'Feet apart, hands together, eyes on the ball — SWING!'",
      "Call out the zone — 'That's a Zone 2! Two points!' — and mark it on the board",
      "Repeat for all 5 swings per kid, tallying points aloud",
      "After 5 swings, announce their total and write it on the board",
      "Next kid steps up. Repeat until everyone has a Round 1 score.",
      "Start Round 2. Before each kid swings, say 'Your score to beat is [X]. You got this!'",
      "After Round 2, celebrate every kid who improved"
    ],
    coaching_points: ["Between Round 1 and Round 2, give each kid ONE specific fix — not two or three, just one. 'Marcus, this time keep your back elbow up.' That's it. One fix at a time is all a 4-year-old can process."],
    common_mistakes: [
      "Kids will focus on other kids' scores and get upset. Fix: Only read each kid their OWN score. Say 'This isn't about beating your friends. It's about beating your OWN score from last time.'",
      "Kids will swing wildly to try to crush the ball. Fix: Say 'Nice and smooth wins the game.' Demonstrate a smooth, level swing vs. a wild hack.",
      "The tee will get knocked over repeatedly. Fix: Stand behind the tee and hold the base with your foot while the kid swings."
    ],
    progressions: "Add a 'bonus point' for any ball hit to the LEFT side of the field (for right-handed hitters) — this teaches pulling the ball. Also add a 'Perfect Swing' bonus point if the coach sees good form.",
    regressions: "Remove the scoring zones entirely. Every contact is 1 point, every miss is 0 points. The goal becomes simply 'How many of your 5 swings can you make contact?' Use a larger wiffle ball if needed.",
    fun_factor: 4,
    week_introduced: 1,
  },
  {
    name: "Coach Pitch Challenge",
    category: "hitting",
    duration_minutes: 8,
    min_kids: 2, max_kids: 4, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["batting tee", "wiffle balls (10+)", "bat (youth)", "bucket"],
    setup_instructions: "Set up the batting tee at home plate. Coach kneels 8-10 feet in front of home plate, slightly to the throwing-arm side. Keep a bucket of wiffle balls within arm's reach. Place the tee right next to the batter so it's ready for immediate use. Second coach or parent stands behind the batter to manage the lineup.",
    how_to_explain_to_kids: "Here's how this works. I'm going to toss you THREE balls — nice and easy, right to your bat. Try to hit them! If you hit at least one, awesome! After your three pitches, you get two more swings off the tee. So everybody gets to hit the ball today, whether it's from me or from the tee. Ready? Batter up!",
    step_by_step: [
      "First batter steps up. Coach kneels 8-10 feet away with bucket of wiffle balls.",
      "Coach says 'Ready? Here it comes!' and lobs the first wiffle ball underhand, aiming for the kid's belt-level sweet spot in a gentle arc",
      "If the kid hits it, celebrate. If they miss, say 'Good try, two more!'",
      "Throw pitch 2 and pitch 3 with the same arc and location. Do NOT speed up or change location.",
      "After 3 pitches, the kid immediately gets 2 swings off the tee. This ensures every kid makes contact.",
      "For the tee swings, place the ball, remind them of one quick cue, and let them swing.",
      "After tee swings, next kid steps up. Rotate quickly.",
      "If a kid hits all 3 pitches, skip the tee and give them 2 more pitched balls as a reward",
      "Go through the lineup twice if time allows"
    ],
    coaching_points: ["Your toss consistency matters more than anything the kid does. Practice your underhand lob before the drill — you want the ball arriving at the same spot and speed every time. Kneel on one knee for a consistent release point. Aim for the batter's belt buckle."],
    common_mistakes: [
      "Coach throws too fast or too flat. Fix: The toss should be a big, slow rainbow arc — peak at 6 feet, land at belt height. Think of lobbing a ball to a toddler, not pitching.",
      "Kids will swing before the ball arrives because they're excited. Fix: Say 'Wait... wait... NOW!' as the ball floats in.",
      "Kids will step backwards when the ball comes toward them. Fix: Put a glove or cone 6 inches in front of their back foot and say 'Step OVER the glove toward me when you swing.'",
      "Kids get discouraged after missing 3 pitches. Fix: That's exactly why the tee rounds exist. Get them to the tee, let them crush it, and say 'GREAT hit! See, you've got a great swing.'"
    ],
    progressions: "Increase to 5 pitched balls and only 1 tee swing. Move the coach back to 12-15 feet. For advanced kids, throw gentle overhand pitches instead of underhand lobs.",
    regressions: "Reduce to 1-2 pitches and 3-4 tee swings. Move the coach closer (6 feet) and toss even slower. If a kid is terrified of the ball, skip pitching entirely for that kid.",
    fun_factor: 5,
    week_introduced: 4,
  },
  {
    name: "Wiffle Ball Derby",
    category: "hitting",
    duration_minutes: 8,
    min_kids: 2, max_kids: 5, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["batting tee", "wiffle balls (15+)", "bat (youth)", "5 cones"],
    setup_instructions: "Set the tee at home plate. Place 5 cones in a straight line heading toward center field at 15 feet, 25 feet, 35 feet, 45 feet, and 55 feet. Label them as Single, Double, Triple, Home Run, and MEGA BLAST. Have 15+ wiffle balls ready. One kid or second coach stands in the outfield as a shagger.",
    how_to_explain_to_kids: "We're having a HOME RUN DERBY! You get 5 big swings. That first cone is a Single, then Double, then Triple, then Home Run, and that wayyyyy out there cone? That's a MEGA BLAST! Nobody's ever hit a Mega Blast before. I wonder if anyone today can do it? Let's find out!",
    step_by_step: [
      "Hype it up — 'Ladies and gentlemen, welcome to the Wiffle Ball Derby!' Use a dramatic announcer voice.",
      "First batter steps up. Adjust tee to belt height. Place wiffle ball.",
      "Say 'The crowd is watching... here's the windup... SWING!' — build drama before every swing",
      "After the hit, call out what it was — 'That's a DOUBLE! The crowd goes wild!' Have waiting kids cheer.",
      "Quickly reload the tee. Keep the pace fast — 5 swings should take about 90 seconds per kid.",
      "Track each kid's best single hit — the goal is one big blast",
      "After all 5 swings, announce the batter's best",
      "Next batter up. Continue until everyone has gone.",
      "Final round: each kid gets ONE championship swing. Biggest hit wins the Derby.",
      "Celebrate the winner but give every kid a fun title — 'Fastest Swinger,' 'Best Stance,' 'Loudest Hitter'"
    ],
    coaching_points: ["Let them swing HARD. This is the one drill where you don't worry about perfect mechanics — it's about effort and excitement. The only cue: 'Swing through the ball, don't stop your bat!' This encourages full follow-through naturally."],
    common_mistakes: [
      "Kids will try to uppercut to launch the ball high. Fix: Only for extreme cases, say 'Swing straight through like you're trying to knock that cone over, not hit an airplane.'",
      "Kids will whiff when swinging hard because they lose balance. Fix: Before their swing, say 'Strong legs! Keep your feet stuck to the ground like glue.'",
      "Balls won't go far because wiffle balls are light. Fix: Set the cones at realistic distances. If nobody is reaching 'Home Run,' move the cones closer.",
      "Some kids will get upset they didn't win. Fix: Create multiple awards. 'Best Swing,' 'Most Improved,' 'Loudest Crack.'"
    ],
    progressions: "Switch from tee to coach soft-toss. Add an elimination round: kids with the top 2 distances face off head-to-head. Move the cones 5 feet farther out each week.",
    regressions: "Move all cones 5 feet closer. Use jumbo wiffle balls. Count total hits out of 5 instead of distance. Celebrate any contact as a 'derby hit.'",
    fun_factor: 5,
    week_introduced: 3,
  },
  {
    name: "Target Hitting",
    category: "hitting",
    duration_minutes: 8,
    min_kids: 2, max_kids: 4, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["batting tee", "wiffle balls (10+)", "bat (youth)", "5 cones", "hula hoop or bucket"],
    setup_instructions: "Set the tee at home plate. Place 5 targets in the field: one hula hoop flat on the ground at 20 feet straight ahead, one cone at 25 feet to the left, one cone at 25 feet to the right, one bucket at 30 feet straight ahead, and one cone at 15 feet straight ahead (the 'easy target'). Hula hoop = 5 points, bucket = 10 points (ball must go IN), side cones = 3 points, easy cone = 1 point.",
    how_to_explain_to_kids: "See all those targets out there? We're going to try to HIT them with the ball! That hula hoop is worth 5 points — the ball has to land inside it. And that bucket? TEN POINTS if you get it in! That's almost impossible but let's see if anyone can do it! You get 5 swings. Ready? Pick your target!",
    step_by_step: [
      "Walk the kids out to see each target up close before starting",
      "First batter steps up. Adjust tee height. Place wiffle ball.",
      "Before each swing, ask 'Which target are you going for?' — this makes them THINK about direction",
      "After each hit, call out what they were closest to",
      "Even misses get encouragement — 'Ooh, that went left! Try the left cone next swing!'",
      "Keep a running tally. Each kid gets 5 swings per round.",
      "After each batter, quickly gather balls or have second coach shagging",
      "Run 2 rounds if time allows. Between rounds, ask 'What are you going to do different?'",
      "End by letting each kid take one 'golden swing' aimed at the bucket"
    ],
    coaching_points: ["This drill secretly teaches directional hitting. When a kid says 'I'm going for the left cone,' they'll naturally adjust their swing. Don't explain HOW to hit left vs. right — just let them experiment."],
    common_mistakes: [
      "Kids will not understand aiming — they'll just swing and hope. Fix: For the first round, simplify to one target: the easy cone 15 feet ahead. Say 'Just try to roll it to that cone.'",
      "Kids will get frustrated that they can't control direction. Fix: Reframe every hit as a positive. At this age, controlling direction is very advanced — contact in any direction is a win.",
      "The targets will get knocked over. Fix: Push cone bases firmly into the grass. If a kid actually hits a cone, make it a HUGE celebration.",
      "Kids will spend too long choosing a target. Fix: Give them 5 seconds — 'Pick in 5... 4... 3... 2... 1... SWING!'"
    ],
    progressions: "Remove the easy cone and add a farther target at 40 feet. Try coach soft-toss instead of the tee. Add a 'combo bonus' where hitting 2 different targets in 5 swings earns 5 bonus points.",
    regressions: "Use only 2 targets: the easy cone and the hula hoop, both at 15 feet. Give points for 'closest to the hoop.' Any contact earns 1 point.",
    fun_factor: 4,
    week_introduced: 4,
  },
  {
    name: "Batting Stance Freeze",
    category: "hitting",
    duration_minutes: 7,
    min_kids: 2, max_kids: 6, min_coaches: 1, max_coaches: 1,
    skill_level_target: "all",
    equipment: ["bat (youth) for each kid or 2-3 to share", "wiffle balls (6+)", "batting tee"],
    setup_instructions: "Line up all kids side by side in the infield grass, about 4 feet apart. Each kid holds a bat (or shares). No tee needed for the first part — this is a dry-swing drill. For the second part, set up one tee at home plate. Coach stands facing the line, about 8 feet in front.",
    how_to_explain_to_kids: "We're going to practice our swing and then FREEZE like a statue! I'm going to count to three, you're going to swing, and then when I say FREEZE you hold still and DON'T MOVE. Like a statue! If you wobble, you're out! Let's see who can freeze the longest. Ready?",
    step_by_step: [
      "Have all kids hold their bats and get into batting stance. Walk down the line and adjust each kid — feet shoulder-width apart, knees slightly bent, hands together near the back shoulder.",
      "Stand in front of the group and say 'One... two... three... SWING!' — all kids swing together at an imaginary ball.",
      "Immediately yell 'FREEZE!' — all kids must hold their follow-through position",
      "Walk down the line and check each kid's finish position. Gently adjust: push the bat further around if they stopped short, shift weight to the front foot.",
      "Hold the freeze for 5 seconds. Anyone who moves or drops their bat does 3 jumping jacks.",
      "Repeat the swing-and-freeze 5 times. Each time, challenge them to freeze longer.",
      "After the dry swings, move to the tee one at a time. Each kid takes a real swing and freezes.",
      "End with a 'championship freeze' — everyone swings together and whoever holds their freeze the longest wins"
    ],
    coaching_points: ["The finish position tells you everything about the swing. If they freeze with the bat low and their weight on the back foot, the swing was wrong. You want: bat wrapped around the front shoulder, belly button facing the pitcher, weight on the front foot. Fix the freeze and you fix the swing."],
    common_mistakes: [
      "Kids will swing with one hand and let the other hand fly off the bat. Fix: Before each swing, say 'Glue hands! Both hands stay on the bat the WHOLE time.'",
      "Kids will fall over during the freeze because they have no balance. Fix: Have them widen their stance by 2 inches. Say 'Wider feet! Strong base!'",
      "Kids will get bored with dry swings quickly. Fix: Keep dry-swing phase to 3-4 minutes max, then move to the tee. Add variety — 'This time, swing in slow motion!'",
      "Kids will not follow through — they'll stop the bat at the contact point. Fix: Say 'Swing through the ball and hug yourself with the bat.'"
    ],
    progressions: "Add a balance challenge: after the freeze, have them lift their back foot off the ground. Also try freeze-at-different-points: freeze at the start (check stance), freeze mid-swing (check bat path), freeze at the end (check follow-through).",
    regressions: "Skip the freeze and just focus on swinging together as a group. For kids who can't hold a bat properly, let them swing without a bat. Reduce freeze time to 2-3 seconds.",
    fun_factor: 3,
    week_introduced: 2,
  },
  {
    name: "Switch Hitter Fun",
    category: "hitting",
    duration_minutes: 7,
    min_kids: 2, max_kids: 4, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["batting tee", "wiffle balls (10+)", "bat (youth)"],
    setup_instructions: "Set up the tee at home plate. Have 10+ wiffle balls ready. The key is in the instruction, not the equipment. Make sure you know which side each kid normally bats from before you start.",
    how_to_explain_to_kids: "Okay, who wants to try something totally crazy? We're going to hit from the OTHER side! If you normally stand on this side — now you're going to stand on THAT side. It's going to feel super weird and that's the whole point! Even real Major League players do this. Don't worry about hitting it far. Just try to hit the ball. Ready? This is going to be so silly!",
    step_by_step: [
      "First, have each kid take 2 normal swings from their regular side for confidence",
      "Now switch them. Physically reposition them — move their feet, put their hands in the new grip, and turn their body.",
      "Say 'This feels weird, right? That's totally normal! You're learning something brand new.'",
      "Have them take a dry swing (no ball) from the new side. Watch for the grip issue.",
      "Place a wiffle ball on the tee. Say 'Just try to touch the ball with the bat.'",
      "Let them take 5 swings from the switch side. Celebrate ANY contact.",
      "After 5 switch swings, give them 2 more normal swings to 'reset' and end on a confident note.",
      "Next kid steps up. Repeat the process.",
      "End by asking 'Was that harder? Which side feels better?' — gets them thinking about their swing"
    ],
    coaching_points: ["This drill is NOT about developing switch hitters at age 4. It's about body awareness and coordination. When a kid swings from the opposite side, they have to THINK about every movement that's normally automatic. This conscious thinking actually improves their regular swing too."],
    common_mistakes: [
      "Kids will refuse to try the other side. Fix: Pick up a bat and swing from your non-dominant side — look silly, whiff on purpose, laugh at yourself. Peer pressure will do the rest once one kid tries it.",
      "Kids will put their hands in the wrong position. Fix: Stand behind them and physically place their hands each swing.",
      "Kids will turn their feet but not their body. Fix: Grab them gently by the shoulders and point their belly button toward home plate.",
      "Kids will get frustrated and want to go back to their normal side. Fix: Let them! Say 'Great job trying! That was so brave!' Never force this drill."
    ],
    progressions: "Challenge kids to see how many balls they can hit out of 5 from each side and compare. For advanced kids, alternate every swing — right, left, right, left.",
    regressions: "Skip switch hitting if a kid is resistant. For kids willing to try, use a jumbo wiffle ball. Reduce to 3 switch swings. Hold the bat WITH the kid for the first switch swing.",
    fun_factor: 4,
    week_introduced: 7,
  },
];
