export const fieldingDrills = [
  {
    name: "Scoop and Score",
    category: "fielding",
    duration_minutes: 7,
    min_kids: 2, max_kids: 10, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["1 bucket or large cone as target", "6 tennis balls or soft training balls", "4 cones"],
    setup_instructions: "Set up on the infield grass between the pitcher's mound and second base. Place a bucket (or tall cone) at second base — this is the scoring target. Set 4 cones in a line along the edge of the infield dirt, each about 6 feet apart — these are the fielding stations. Coach stands 10 feet in front of the cone line with all the balls. Kids line up single-file behind the first cone. If you have a second coach, place them near the bucket to retrieve balls and cheer when one goes in.",
    how_to_explain_to_kids: "We're going to scoop up grounders like ice cream scoops! You get low, scoop the ball with your glove, and then throw it into that bucket over there. If you get it in the bucket, that's a POINT for the team! We're going to try to get ten points together. Ready? Get your ice cream scoopers ready!",
    step_by_step: [
      "Line kids up behind the first cone — first kid steps forward to the fielding spot and gets in ready position (knees bent, glove on the ground)",
      "Coach rolls a grounder on the grass directly at the kid from 10 feet away — roll it gently so it stays on the ground, no bouncing",
      "Kid fields the ball by getting their glove flat on the ground and scooping up with the bare hand covering on top — say 'Scoop it like ice cream!' as they do it",
      "Once the ball is secured, kid turns toward the bucket at second base (about 15 feet away) and throws underhand or overhand trying to get it in or near the bucket",
      "If the ball goes in the bucket, the whole team yells 'SCORE!' and coach marks one point on the ground with a finger",
      "Kid jogs to the back of the line, next kid steps up immediately — keep the pace fast so nobody waits more than 30 seconds",
      "After all kids go through once, move the rolling position 2 feet to the left so the grounder comes at a slight angle",
      "Keep a running team score and set a goal — 'Can we get 10 scoops before time runs out?'"
    ],
    coaching_points: ["Only coach one thing: glove flat on the ground BEFORE the ball gets there. Say 'Beat the ball to the spot — glove down first, then the ball rolls in!' If the glove is on the ground early, everything else works."],
    common_mistakes: [
      "Kids will stab at the ball with their glove instead of getting it on the ground first. Fix: Before rolling the ball, say 'Show me your glove on the grass.' Wait until you literally see the glove leather touching dirt, THEN roll. Do this every single time for the first round.",
      "Kids will try to pick the ball up with just the glove hand and it squirts out. Fix: Say 'Alligator mouth! Top hand chomps down!' and demonstrate the bare hand closing on top of the glove like an alligator jaw. Have them practice the chomping motion three times with no ball before rolling one.",
      "Throws to the bucket will go everywhere — over the fence, into the dugout, sideways. Fix: Don't worry about accuracy at all for weeks 1-2. Just say 'Throw it NEAR the bucket' and count anything within 5 feet as a point. The scooping is the real lesson.",
      "Kids will field the ball then stand there holding it, forgetting to throw. Fix: The instant they field it, yell 'BUCKET!' as a trigger word. Practice the sequence without a ball first: mime scoop, spin, throw."
    ],
    progressions: "Roll the ball harder so it moves faster across the grass. Move the coach position to a 45-degree angle so kids have to field to one side. Shrink the scoring zone — only balls IN the bucket count, not near it. Add a second bucket at a different base so kids have to choose which target to throw to.",
    regressions: "Roll the ball slower and from only 5 feet away. Remove the bucket entirely — just focus on scooping and holding the ball up to show coach. Use a larger ball like a foam softball that's easier to scoop. Let kids field without a glove at first so they learn the hand position, then add the glove.",
    fun_factor: 4,
    week_introduced: 1,
  },
  {
    name: "Hot Potato Grounders",
    category: "fielding",
    duration_minutes: 6,
    min_kids: 3, max_kids: 12, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["4-6 tennis balls", "1 phone or watch for timing"],
    setup_instructions: "Use the infield dirt area. Spread kids out in a large circle about 8 feet apart from each other — use the pitcher's mound as the center of the circle. If you have 6 or fewer kids, make the circle smaller (5 feet apart). Coach stands in the middle of the circle with all the balls. If you have a second coach, they stand outside the circle behind the kids to stop balls that get past and toss them back to the center coach.",
    how_to_explain_to_kids: "This ball is a HOT POTATO! When I roll it to you, it's BURNING your glove — you have to scoop it up and get rid of it FAST by rolling it to someone else in the circle! If you hold it for more than three seconds, you're BURNT! I'm going to add more and more hot potatoes until there's a BUNCH flying around. Ready? Don't get burned!",
    step_by_step: [
      "Have all kids stand in a circle in fielding ready position — knees bent, glove out front, bare hand ready",
      "Coach rolls ONE ball on the ground to any kid in the circle — say 'HOT POTATO!' as you roll it",
      "That kid scoops it up and immediately rolls it on the ground to a different kid across the circle — they must get rid of it within 3 seconds",
      "The receiving kid scoops and rolls to someone else — the ball keeps moving around the circle, always on the ground",
      "After 30 seconds of one ball moving smoothly, coach adds a SECOND ball into the circle without warning — say 'ANOTHER HOT POTATO!'",
      "Now two balls are rolling around the circle at the same time — kids have to stay alert for balls coming from any direction",
      "Every 30 seconds, add one more ball until there are 3-4 balls flying around and the chaos peaks",
      "When it gets too crazy and balls are everywhere, yell 'FREEZE!' — anyone holding a ball does 3 jumping jacks, then reset and start over with one ball"
    ],
    coaching_points: ["Only coach one thing: eyes on the ball ALL the way into the glove. Say 'Watch the ball go into your ice cream scoop — don't look up until it's in there!' Kids look at where they want to throw before they catch, and that's when they miss."],
    common_mistakes: [
      "Kids will throw the ball in the air instead of rolling it on the ground. Fix: Every time a ball goes airborne, stop play and say 'Ground balls only! It has to touch the grass the whole way!' Demonstrate a firm roll along the ground. If a kid keeps throwing it, have them push the ball with two hands from between their legs like a bowling ball.",
      "Kids will panic when multiple balls are in play and freeze up. Fix: If a kid freezes, call their name and point at the incoming ball — 'Sarah! Hot potato coming!' This breaks the deer-in-headlights moment. Also, never put more than 2 balls in play for the first two practices.",
      "Kids will roll the ball to the same friend every time. Fix: Make a rule — 'You can't send it to the same person twice in a row!' Call out who to roll to if needed: 'Send it to Jake!'",
      "Kids will stand straight up between rolls instead of staying in ready position. Fix: Every time you add a new ball, say 'Show me your ready position — knees bent, hands low!' Make it a quick reset before the chaos resumes."
    ],
    progressions: "Speed up the pace by counting down out loud — 'Three! Two! One! Get rid of it!' — so kids learn to field and release faster. Add a fourth ball for maximum chaos. Have kids take one step back to make the circle bigger so rolls travel further.",
    regressions: "Use only one ball for the entire drill. Slow the pace way down — no time pressure, just focus on proper scooping. Shrink the circle so kids are only 4 feet apart and the ball doesn't have to travel far. Let kids use two hands with no glove so they focus on hand position.",
    fun_factor: 5,
    week_introduced: 2,
  },
  {
    name: "Fly Ball Frenzy",
    category: "fielding",
    duration_minutes: 7,
    min_kids: 2, max_kids: 8, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["6-8 tennis balls", "1 bucket or bag for balls"],
    setup_instructions: "Set up in the outfield grass where there's plenty of soft ground for kids to move around. Place the bucket of tennis balls near the coach's spot. Coach stands on the outfield grass about 15 feet in front of the first base line. Kids line up single-file behind a cone set 12 feet from the coach. Make sure there's at least 30 feet of open grass behind and to each side of the fielding spot — balls will get past kids frequently. If you have a second coach, they shag missed balls.",
    how_to_explain_to_kids: "I'm going to throw pop flies up in the air like little birds, and you're going to catch them! But we're using tennis balls because they're easier to catch and they don't hurt. Put your hands up like you're making a basket — see? Like you're holding a baby bird that fell out of a tree. Catch the ball in your bird basket! If you drop it, no big deal — baby birds bounce!",
    step_by_step: [
      "Have the first kid step forward to the fielding spot and face the coach — NO gloves for this drill, bare hands only",
      "Demonstrate the catching position — both hands up near the face, fingers spread, palms facing up and slightly cupped like a basket or nest, thumbs almost touching",
      "Toss the first tennis ball underhand straight up so it comes down right to the kid's chest level — only 5-6 feet high for the first round",
      "If the kid catches it, celebrate big — 'You saved the baby bird!' If they drop it, say 'Almost! The bird bounced but that's okay — let's try again!'",
      "Each kid gets 3 tosses per turn, then rotates to the back of the line",
      "On the second round, toss the ball slightly to the left or right (3 feet off-center) so kids have to shuffle their feet to get under it",
      "On the third round, increase the height to about 10 feet — say 'This bird is flying HIGH!' and give kids time to track it coming down",
      "Keep count of total team catches and set a goal — 'Can we save 20 baby birds today?'"
    ],
    coaching_points: ["Only coach one thing: get your feet UNDER the ball before it comes down. Say 'Move your feet first, then put your basket up!' Kids want to reach with their arms, but the real skill is moving to the right spot. If their nose is pointed at the ball, their hands are in the right place."],
    common_mistakes: [
      "Kids will try to catch the ball with arms fully extended overhead like catching a football. Fix: Say 'Bring the basket to your face — catch it right here!' and hold your hands in front of your nose. Toss a ball right to their face-level so the basket position works naturally. Then gradually increase height.",
      "Kids will close their eyes right before the ball arrives. Fix: This is totally normal for 4-year-olds. Say 'Watch the ball the WHOLE way — keep your eyes on the bird!' Use tennis balls specifically because even if they hit the kid in the face, it doesn't hurt badly. It takes 3-4 practices before eye-closing stops.",
      "Kids will stand flat-footed and reach instead of moving to the ball. Fix: Before each toss, say 'I'm going to throw it somewhere tricky — you have to MOVE!' Then deliberately toss it 2-3 feet to one side so they MUST shuffle. Praise the foot movement, not the catch.",
      "Kids will trap the ball against their chest instead of catching in their hands. Fix: Don't correct this for weeks 1-3. Chest trapping is a perfectly fine intermediate step for 4-year-olds. Once they're confident, start saying 'Can you catch it before it touches your shirt?'"
    ],
    progressions: "Increase toss height to 12-15 feet. Toss the ball further to the left or right so kids have to run 5-6 feet to get under it. Add gloves once bare-hand catching is consistent. Have two kids field at the same time and call 'I got it!' before catching — this teaches communication.",
    regressions: "Toss the ball only 3 feet in the air — basically a soft lob right to their hands. Use foam balls instead of tennis balls if a kid is scared. Let kids trap the ball against their body with no correction. Stand only 5 feet away so the toss is very short and predictable.",
    fun_factor: 4,
    week_introduced: 2,
  },
  {
    name: "Barehand Catch",
    category: "fielding",
    duration_minutes: 7,
    min_kids: 2, max_kids: 10, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["6 foam balls or soft fabric training balls", "4 cones"],
    setup_instructions: "Set up on the infield grass. Place 4 cones in a straight line, each about 8 feet apart — these create individual stations. Pair kids up and have each pair stand across from each other at a station, 6 feet apart. If you have odd numbers, the extra kid partners with the coach. All gloves go in a pile by the dugout — nobody wears a glove for this drill. Coach roams between stations. Second coach monitors the far stations.",
    how_to_explain_to_kids: "Okay, everybody take OFF your gloves! We're catching with our bare hands like REAL ninjas! Ninjas don't need gloves — they use their HANDS. I'm going to teach you the secret ninja catch. You make a diamond shape with your hands — see how my thumbs touch and my pointer fingers touch? That's the ninja diamond! Everything goes right into the diamond. Let's do it!",
    step_by_step: [
      "Have all kids remove gloves and set them aside — make a big deal of this: 'Gloves are for regular players. We're NINJAS right now!'",
      "Demonstrate the hand position — thumbs together, index fingers together, palms open, forming a diamond/triangle window between the hands. Hold it up and say 'Look through the window — can you see me through your diamond?'",
      "Have every kid make the diamond shape and look through it at the coach to confirm they have the right hand position",
      "Partners face each other at 6 feet apart. One partner holds a soft foam ball. Say 'Toss it underhand, nice and easy, right into your partner's diamond!'",
      "The catching partner holds the diamond up at chest height and watches the ball come in — when the ball hits their palms, they squeeze both hands together to trap it",
      "Each partner tosses 5 times, then they switch roles. Coach walks between pairs saying 'Show me your diamond!' before each toss",
      "After both partners go, have pairs take one step back (now 8 feet apart) and repeat",
      "End with a 'Ninja Challenge' — which pair can complete 10 catches in a row without dropping? Count out loud as a team."
    ],
    coaching_points: ["Only coach one thing: soft hands. Say 'When the ball touches your hands, let your hands go back a tiny bit — like you're catching an egg. If you keep your hands stiff, the egg breaks and the ball bounces away!' Demonstrate by catching and letting your hands give with the ball."],
    common_mistakes: [
      "Kids will hold their hands too far apart and the ball goes right through the gap. Fix: Have them start with hands actually touching — thumbs glued together, fingers glued together — then open just enough to see through the diamond. Say 'If you can fit your head through the diamond, it's TOO big!'",
      "Kids will turn their head away or flinch when the ball arrives. Fix: Use the absolute softest foam balls you can find — the kind that compress to nothing when squeezed. Gently toss one into their face and say 'See? Doesn't hurt at all!' Once they trust that, the flinching stops within a few tosses.",
      "The throwing partner will throw too hard or too high. Fix: Teach the toss first before any catching. Say 'Throw it like you're tossing it to a baby — super soft, right to their chest.' If a kid keeps throwing wild, have them take a step closer.",
      "Kids will catch with one hand instead of two. Fix: Say 'Ninjas always use two hands — one hand is only HALF ninja power!' Every time you see a one-hand catch attempt, call it out playfully: 'Both hands, full ninja power!'"
    ],
    progressions: "Move partners back to 10 feet apart. Switch from foam balls to tennis balls. Add a bounce — throw the ball so it bounces once before reaching the partner, and they catch the bounce with the diamond hands. Introduce 'quick catch' where they must catch and throw back within 2 seconds.",
    regressions: "Move partners to 4 feet apart — basically arm's length. Use a larger foam ball that's easier to trap. Coach stands behind the catcher and physically cups their hands into diamond position for the first few catches. Let kids catch by trapping the ball against their chest — just get them comfortable with a ball coming toward them.",
    fun_factor: 3,
    week_introduced: 1,
  },
  {
    name: "Triangle Toss",
    category: "fielding",
    duration_minutes: 8,
    min_kids: 3, max_kids: 12, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["3-4 soft training balls or tennis balls", "6 cones"],
    setup_instructions: "Set up on the infield grass using the natural triangle formed by the bases. Place 3 cones in a triangle shape, each 10 feet apart — roughly the distance from the pitcher's mound to each baseline. If you have more than 3 kids, set up multiple triangles using the full infield. Each triangle gets one ball. Place the extra cones to mark a second or third triangle if needed, spacing them at least 10 feet away from each other so groups don't interfere. Coach floats between triangles. Second coach takes the far triangle.",
    how_to_explain_to_kids: "We're going to play catch in a triangle! You've got three people and ONE ball. You throw it to the person on your left — always to your left! So the ball goes around the triangle like a merry-go-round. We're going to count how many catches we can make without dropping it. If we get to TEN, everybody in the triangle gets a high-five from coach! Ready? Throw, catch, throw, catch — keep it going!",
    step_by_step: [
      "Split kids into groups of 3 and assign each group to a triangle of cones — have each kid stand at one cone",
      "Give one ball to one kid in each triangle and point out who they throw to — 'You throw to her, she throws to him, he throws back to you. Always go that way!'",
      "Have every group do a practice round — just 3 throws, one full trip around the triangle — with the coach watching and correcting",
      "Once each group completes a practice round, start the counting challenge — 'Okay, now count your catches out loud! ONE! TWO! THREE!'",
      "When a ball is dropped, the count resets to zero — say 'Reset! No worries, start over!'",
      "Coach circulates between groups, spending about 20 seconds at each to correct one thing — throwing technique or catching position",
      "After 3 minutes, switch the direction — 'Now throw to your RIGHT! It's going the other way!'",
      "For the last 2 minutes, challenge all triangles to hit their record — 'Every group try to beat your best number!'"
    ],
    coaching_points: ["Only coach one thing: step toward your target when you throw. Say 'Point your belly button at the person you're throwing to, then step with your front foot RIGHT at them, then throw.' Feet first, then throw. If the belly button and step are aimed at the target, the ball usually goes there."],
    common_mistakes: [
      "Kids will forget who they're supposed to throw to and throw to the wrong person. Fix: Before starting, do a 'point drill' — every kid points at the person they throw to and says that person's name out loud. Do this twice. When a kid forgets mid-drill, say 'Who do you throw to?' and make them point before throwing.",
      "Throws will go way over kids' heads or bounce in the dirt 3 feet in front of them. Fix: Stand behind the thrower and say 'See their chest? Aim for the letters on their shirt.' Then physically point their throwing arm at the target before they release. Accuracy comes very slowly at this age — celebrate any throw that's within arm's reach of the catcher.",
      "One kid in the group will dominate and the other two just stand there. Fix: The structure prevents this since the ball must go around the triangle. But if a kid holds the ball too long, count out loud: 'One Mississippi, two Mississippi — throw it!' Set a 3-second hold limit.",
      "Kids will move off their cone and drift toward each other until they're standing in a tight clump. Fix: Say 'Freeze on your cone! Your feet have to stay touching your cone!' Check the triangles every 60 seconds and wave kids back to their cones."
    ],
    progressions: "Move the cones to 15 feet apart. Have kids throw to the person two spots away instead of the person next to them — this requires a longer and more accurate throw. Add a second ball so two balls are circling the triangle at once. Time the group and see how many catches they make in 60 seconds.",
    regressions: "Shrink the triangle to 6 feet apart. Let kids roll the ball on the ground instead of throwing in the air. Coach stands in the middle of the triangle and redirects any wild throws back to the right kid. Use a larger foam ball that's easier to catch.",
    fun_factor: 3,
    week_introduced: 3,
  },
  {
    name: "Wall Ball",
    category: "fielding",
    duration_minutes: 7,
    min_kids: 1, max_kids: 6, min_coaches: 1, max_coaches: 1,
    skill_level_target: "all",
    equipment: ["3-4 tennis balls", "1 bucket or bag for balls"],
    setup_instructions: "Set up directly in front of the backstop behind home plate. The backstop fence or wall is the target. Place a cone 8 feet from the backstop — this is the throwing line. Kids line up single-file behind a second cone 5 feet behind the throwing line. Make sure the ground between the throwing line and the backstop is clear of gravel, rocks, or equipment so balls bounce cleanly back. If the backstop is chain-link fence, the ball will die on impact — use a solid wall or concrete backstop instead. If no solid wall exists, lean a large board or plywood against the fence.",
    how_to_explain_to_kids: "See that wall? We're going to throw the ball AT the wall and then catch it when it bounces back! It's like the wall is throwing it back to you — the wall is your practice buddy! Throw it hard and it comes back fast. Throw it soft and it comes back soft. Let's see if you can throw and catch it FIVE times in a row without dropping it!",
    step_by_step: [
      "First kid steps to the throwing line cone, 8 feet from the wall, facing the backstop with a tennis ball",
      "Demonstrate the drill yourself first — throw overhand into the wall at about waist height, then field the rebound like a grounder. Show that hitting the wall higher makes a fly ball return, and hitting it lower makes a grounder return",
      "Kid throws the ball into the wall — for the first round, have them throw gently underhand to get a predictable bounce back",
      "Ball rebounds off the wall and rolls or bounces back — kid gets in fielding ready position and scoops it up",
      "Once fielded, kid throws again immediately — try to keep a continuous rhythm of throw, field, throw, field",
      "Each kid gets 5 throws per turn, then rotates to the back of the line. Count successful catches out loud.",
      "On the second round, have kids try overhand throws — the ball comes back faster and less predictably, which forces quicker reactions",
      "For the final round, have kids try to throw the ball at different heights on the wall to see what kind of rebound they get — 'Can you make it come back as a grounder? Now try to make it bounce up high!'"
    ],
    coaching_points: ["Only coach one thing: ready position BEFORE the ball comes back. Say 'As soon as the ball leaves your hand, get your glove down and your feet wide — the ball comes back FAST!' The throw doesn't matter. What matters is that they're in fielding position before the rebound reaches them."],
    common_mistakes: [
      "Kids will throw the ball and just stand there watching it hit the wall instead of getting ready to field. Fix: Stand next to the kid and the instant they release the ball, tap their knees and say 'DOWN! Get ready!' After 3-4 reps, they'll start dropping into ready position automatically.",
      "The ball will rebound to one side and the kid won't move to it. Fix: Say 'The ball won't come right back to you every time — you have to chase it! Move your feet!' Stand behind them and gently push their hips in the direction the ball is going.",
      "Kids will throw too hard and the ball rockets back past them before they can react. Fix: Say 'Easy throw first! Throw it like you're handing it to the wall, not attacking the wall.' Start with underhand tosses. Increase power only when the kid can consistently field the soft rebounds.",
      "Kids will get bored because there's no competition element. Fix: Add counting — 'How many in a row can you get? Jake got 4, can you beat him?' Write a scoreboard in the dirt with a stick."
    ],
    progressions: "Move the throwing line to 12 feet from the wall so rebounds travel further and faster. Have kids field with their glove and make a throw to a target (bucket at the pitcher's mound) instead of just fielding. Alternate overhand and underhand throws to vary the rebound. Have two kids go simultaneously side by side to add distraction.",
    regressions: "Move the throwing line to 5 feet from the wall so rebounds are very short and slow. Use foam balls instead of tennis balls. Let the ball stop rolling before the kid tries to pick it up — no catching on the bounce, just field a dead ball. Coach stands next to the kid and points at where the ball is going as it rebounds.",
    fun_factor: 3,
    week_introduced: 4,
  },
  {
    name: "Dive and Slide",
    category: "fielding",
    duration_minutes: 8,
    min_kids: 2, max_kids: 10, min_coaches: 1, max_coaches: 2,
    skill_level_target: "all",
    equipment: ["6 tennis balls or foam balls", "4 cones", "1 slip-and-slide or tarp (optional)"],
    setup_instructions: "This drill MUST be on soft, thick outfield grass — check for rocks, sticks, and holes before starting. Set 4 cones in a line about 8 feet apart along the outfield grass, roughly 20 feet behind the second base area. This creates a 'diving lane.' Coach stands 12 feet in front of the diving lane with all the balls. If the grass is wet, it's PERFECT — slides are smoother. If you have a tarp or slip-and-slide, lay it flat on the grass in the diving lane for extra slide distance. Second coach stands behind the diving lane to collect balls that get past kids.",
    how_to_explain_to_kids: "Guess what? This is the ONLY drill where you're SUPPOSED to get dirty! I'm going to roll the ball to the side, and you have to dive on the grass to grab it — like a superhero flying through the air! The dirtier your uniform gets, the better you're doing! Who wants to get the dirtiest? Let's see some superhero dives!",
    step_by_step: [
      "Before any diving, demonstrate the safe dive yourself — show kids how to land on their belly and chest with arms outstretched, chin UP (not tucked), sliding on the grass. Say 'Chin up like Superman flying — look where you're going!'",
      "Have every kid practice a belly flop onto the grass with no ball — just run two steps and slide on their stomach. Do this 3 times to get the giggles out and make sure nobody is scared",
      "Line kids up single-file behind the first cone. First kid steps into the diving lane in ready position, knees bent, hands out front",
      "Coach rolls a ball on the ground to the kid's left or right, about 4 feet to the side — far enough that they can't reach it standing still but close enough that a short dive gets them there",
      "Kid shuffles toward the ball, leaves their feet, and dives onto their belly to trap or grab the ball on the ground — any contact with the ball counts as success",
      "After the dive, kid holds the ball up from the ground and the team cheers — 'GREAT DIVE!' — then kid jogs to the back of the line",
      "Roll to alternating sides — left for one kid, right for the next — so everyone practices diving both directions",
      "For the last 2 minutes, roll the ball a little further to the side (6 feet) so kids have to really commit to the dive"
    ],
    coaching_points: ["Only coach one thing: land on your BELLY, not your knees. Say 'Flat like a pancake — belly on the grass!' Kids instinctively want to drop to their knees first, which hurts and slows them down. A flat belly dive is safer, slides further on grass, and is how real baseball players do it."],
    common_mistakes: [
      "Kids will be scared to dive and will just bend over or fall to their knees. Fix: Make the first 3 minutes just belly-flop practice with no ball. Have them run and slide on the grass like a penguin on ice. Once they're laughing and sliding, THEN introduce the ball. Peer pressure works here — when one kid does a full dive, the others will follow.",
      "Kids will land on their knees or hands, which hurts. Fix: Demonstrate the 'Superman landing' again — arms out front, chest and belly hit at the same time, chin up. Say 'Knees UP, belly DOWN!' If a kid keeps landing on their knees, have them practice from a kneeling position first — just fall forward from their knees to their belly.",
      "Kids will close their eyes during the dive and miss the ball completely. Fix: This is fine. They're 4. Say 'You almost had it — great dive!' and celebrate the effort, not the result. After a few practices, they'll start keeping eyes open because they WANT to catch it.",
      "Parents on the sideline will freak out about diving. Fix: Before the drill, tell parents 'This is a controlled diving drill on soft grass — stains wash out, and this skill prevents injuries in games by teaching kids how to fall safely.' Emphasize it's a SAFETY skill."
    ],
    progressions: "Roll the ball further away (8 feet to the side) so kids have to sprint and dive. Toss short pop-ups to the side so kids have to dive and catch in the air, not on the ground. Add a 'throw from the ground' — after diving, kid must throw the ball from their belly to a standing coach 10 feet away. Wet the grass with a hose for longer slides.",
    regressions: "Forget diving — just have kids shuffle sideways to a ball rolled 2 feet to their side and pick it up. Practice falling safely by having kids stand still and just fall forward onto the grass from a standing position — no running. Roll the ball very slowly and only 2 feet to the side so the kid barely has to move. Use the largest, softest foam ball available.",
    fun_factor: 5,
    week_introduced: 5,
  },
];
